server:
  port: 8080

spring:
  application:
    name: SIKAS
  profiles:
    active: dev  # Change to 'prod' for production environment
  datasource:
    url: your_encrypted_database_url_here
    username: your_encrypted_database_username_here
    password: your_encrypted_database_password_here
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_schema: dbo
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
  sql:
    init:
      mode: always

jwt:
  secret: your_jwt_secret_here
  expiration: 900000 # 15 minutes in milliseconds
  refresh-secret: your_jwt_refresh_secret_here
  refresh-expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    root: INFO
    app: DEBUG
  mask-sensitive: false